services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: rave
      POSTGRES_PASSWORD: 1b29ae1cdc12acadf79db1b9
      POSTGRES_DB: rave
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rave -d rave"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
